# Generated by Django 2.1.5 on 2020-02-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookshelf', '0002_bookshelfrecomend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='size_height',
        ),
        migrations.RemoveField(
            model_name='book',
            name='size_width',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='価格'),
        ),
    ]
