# Generated by Django 2.1.5 on 2020-02-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookshelf', '0004_auto_20200205_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(verbose_name='出版日'),
        ),
    ]
