# Generated by Django 2.1.5 on 2020-02-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookshelf', '0008_remove_bookshelfmaster_small_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreviews',
            name='book_review_star',
            field=models.IntegerField(blank=True, null=True, verbose_name='スターの数'),
        ),
    ]
